### ISSUE TITLE
Bump mmsplice version

### ISSUE THREAD

**Issue by jerome-f** [kircherlab/CADD-scripts#54]
Hi,

I am trying to install CADD-scripts on my local env and the legacy dependency of mmsplice 1.0.1  with concise is giving me problems installing. Since mmsplice 2.x the concise dependency has be integrated into the core api and much of the predictions are 1:1 with the legacy api. would it be possible to bump the version of mmsplice to the most recent version? 

I am trying to have local installation of CADD v1.7.

**Comment by visze** [comment]
Hi Jerome,

Thank you for your request. CADD was trained with MMsplice 1.0.1 and scores are generated with this specific version. Therefore we don't want to upgrade MMsplice because predictions might be different and the scores will be different. This leads to a disagreement with the pre-computated whole genome files. We also see that sometimes scores are totally off when a feature has different values due to versions/environments. We can keep your request and update MMsplice on the next CADD release. 
Of course you can use the newer version in your own code base. But you really have to ensure that predictions on the whole genome are equal.

Best,
Max

**Comment by jerome-f** [comment]
Max @visze 

Thanks for reply and totally agree with that. I canceled the PR I generated for this realizing that any small change can affect the scores overall. But it would be great if the new version can patch the most recent MMSplice. Legacy dependency such as concise, cython=0.29 (current cython is 3.x) etc are going to be affecting code efficiency. Plus the improvement from the new model probably would add to the CADD score in a positive way (can't gauge this at my end). I am having trouble installing the scripts locally due to conflicts. (Snakemake with mamba fails at multiple instances).

**Comment by jerome-f** [comment]
@visze also micromamba is able to solve the environment better.

**Comment by jerome-f** [comment]
@visze and @makirc The core models that are used in mmsplice doesn't look like they have changed since v1.0.1 -> v2.4.0. Check [here ](https://github.com/gagneurlab/MMSplice_MTSplice/tree/master/mmsplice/models) What has been changed is all the infrastructure around it. I am still having trouble installing the mmsplice environment in my cluster. I get TypeError with the metaclass which is very cryptic to solve given everything is outdated 
```

Using TensorFlow backend.
Traceback (most recent call last):
  File "/CADD/src/scripts/lib/tools/MMSplice.py", line 6, in <module>
    from mmsplice.vcf_dataloader import SplicingVCFDataloader
  File "/CADD/envs/conda/d7f147b1cd6acba35d2bf7623abb9dd4_/lib/python3.6/site-packages/mmsplice/__init__.py", line 7, in <module>
    from keras.models import load_model
  File "/CADD/envs/conda/d7f147b1cd6acba35d2bf7623abb9dd4_/lib/python3.6/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/CADD/envs/conda/d7f147b1cd6acba35d2bf7623abb9dd4_/lib/python3.6/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/CADD/envs/conda/d7f147b1cd6acba35d2bf7623abb9dd4_/lib/python3.6/site-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/CADD/envs/conda/d7f147b1cd6acba35d2bf7623abb9dd4_/lib/python3.6/site-packages/keras/backend/__init__.py", line 89, in <module>
    from .tensorflow_backend import *
  File "/CADD/envs/conda/d7f147b1cd6acba35d2bf7623abb9dd4_/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "/CADD/envs/conda/d7f147b1cd6acba35d2bf7623abb9dd4_/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/CADD/envs/conda/d7f147b1cd6acba35d2bf7623abb9dd4_/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 63, in <module>
    from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin
  File "/CADD/envs/conda/d7f147b1cd6acba35d2bf7623abb9dd4_/lib/python3.6/site-packages/tensorflow/python/framework/framework_lib.py", line 25, in <module>
    from tensorflow.python.framework.ops import Graph
  File "/CADD/envs/conda/d7f147b1cd6acba35d2bf7623abb9dd4_/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 53, in <module>
    from tensorflow.python.platform import app
  File "/CADD/envs/conda/d7f147b1cd6acba35d2bf7623abb9dd4_/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 24, in <module>
    from tensorflow.python.platform import flags
  File "/CADD/envs/conda/d7f147b1cd6acba35d2bf7623abb9dd4_/lib/python3.6/site-packages/tensorflow/python/platform/flags.py", line 25, in <module>
    from absl.flags import *  # pylint: disable=wildcard-import
  File "/CADD/envs/conda/d7f147b1cd6acba35d2bf7623abb9dd4_/lib/python3.6/site-packages/absl/flags/__init__.py", line 35, in <module>
    from absl.flags import _argument_parser
  File "/CADD/envs/conda/d7f147b1cd6acba35d2bf7623abb9dd4_/lib/python3.6/site-packages/absl/flags/_argument_parser.py", line 82, in <module>
    class ArgumentParser(Generic[_T], metaclass=_ArgumentParserCache):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

**Comment by jerome-f** [comment]
Hi,

I randomly picked a set of splice/indel variants (n=20,000) genome wide and ran CADD with mmsplice 2.4.0 as well and concurrently submitted the same set of variants for prediction on the server, here is the plot of `RawScore` and `PHRED_score` comparison between the two versions.`_x `used mmsplice 2.4.0,` _y` is from CADD prediction from server.
![PHRED](https://github.com/kircherlab/CADD-scripts/assets/29581226/1c4f2a1f-86df-4e27-b556-03b6c30e766c)
![raw_score](https://github.com/kircherlab/CADD-scripts/assets/29581226/6aa04fe8-4bc5-484a-948c-b8a4aac9b340)

**Comment by jerome-f** [comment]
Outliers above are not splice variants in the new version of MMSplice hence they have NaN in their columns. So essentially the proving the model's PHRED scale (which is relative) still holds for the updated version of MMSplice. Only re-calibrating genome wide predictions to remove variants that are not splice variants should actually be a good thing ?

**Comment by visze** [comment]
I released a new CADD-scripts version [v1.7.1](https://github.com/kircherlab/CADD-scripts/releases/tag/v1.7.1). Maybe you try that one.  Now it is recommended to use apptainer/singularity and all environments are packed within a container and no conda builds are needed (container is 17GB large).  You also need now snakemake 8.

Also I updated the environments. So If you use mamba/conda instead I hope you will not face the issues you had above

**Comment by visze** [comment]
cleaning up issues. please reopen if it still exists
