### ISSUE TITLE
Error creating envs

### ISSUE THREAD

**Issue by boesr** [kircherlab/CADD-scripts#67]
I just tried to install CADD locally. It fails during the creation of the environments. 

```bash
snakemake test/input.tsv.gz --use-conda --conda-create-envs-only --conda-prefix envs/conda \
        --configfile config/config_GRCh38_v1.7.yml --snakefile Snakefile -c 1
Building DAG of jobs...
Your conda installation is not configured to use strict channel priorities. This is however crucial for having robust and correct environments (for details, see https://conda-forge.org/docs/user/tipsandtricks.html). Please consider to configure strict priorities by executing 'conda config --set channel_priority strict'.
Creating conda environment envs/environment_minimal.yml...
Downloading and installing remote packages.
Environment for /home/local-user/test/cadd/CADD-scripts-1.7.orig/envs/environment_minimal.yml created (location: envs/conda/2ca8e7cf71a98eb9bff084cf105bfb96_)
Traceback (most recent call last):
  File "/home/local-user/.conda/envs/cadd/lib/python3.11/weakref.py", line 666, in _exitfunc
    f()
  File "/home/local-user/.conda/envs/cadd/lib/python3.11/weakref.py", line 590, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/local-user/.conda/envs/cadd/lib/python3.11/tempfile.py", line 933, in _cleanup
    cls._rmtree(name, ignore_errors=ignore_errors)
  File "/home/local-user/.conda/envs/cadd/lib/python3.11/tempfile.py", line 929, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "/home/local-user/.conda/envs/cadd/lib/python3.11/shutil.py", line 752, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/home/local-user/.conda/envs/cadd/lib/python3.11/shutil.py", line 672, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/home/local-user/.conda/envs/cadd/lib/python3.11/shutil.py", line 672, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/home/local-user/.conda/envs/cadd/lib/python3.11/shutil.py", line 672, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  [Previous line repeated 4 more times]
  File "/home/local-user/.conda/envs/cadd/lib/python3.11/shutil.py", line 683, in _rmtree_safe_fd
    onerror(os.rmdir, fullname, sys.exc_info())
  File "/home/local-user/.conda/envs/cadd/lib/python3.11/shutil.py", line 681, in _rmtree_safe_fd
    os.rmdir(entry.name, dir_fd=topfd)
OSError: [Errno 39] Directory not empty: 'envs'
```

Beforehand I created an cadd environment in my local `.conda` folder to install Snakemake. I also tried the install script, which shows the same error message.

**Comment by visze** [comment]
First of all take the strict priority channel warning seriously!

Not sure what causes your error. But we try to provide a do keep Image with
the environments soon so that installing them will not be necessary (but
retrieving the docker image via apptainer).

boesr ***@***.***> schrieb am Mo., 10. Juni 2024, 11:47:

**Comment by boesr** [comment]
Thanks for for the answer. Since we want to provide the software within our cluster a native environment would be a better for us. But I appreciate the docker image.

**Comment by visze** [comment]
I released a new CADD-scripts version [v1.7.1](https://github.com/kircherlab/CADD-scripts/releases/tag/v1.7.1). Maybe you try that one.  Now it is recommended to use apptainer/singularity and all environments are packed within a container and no conda builds are needed (container is 17GB large).  You also need now snakemake 8.

**Comment by visze** [comment]
cleaning up issues. please reopen if it still exists
